name: Publishable

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  publish_dry_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Publish dry run
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          dryRunOnly: true